language: php

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - travis_retry composer require "illuminate/contracts=^5.8" --dev --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
